# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: updater.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='updater.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rupdater.proto\"!\n\x08\x46Version\x12\x15\n\rVersionString\x18\x01 \x01(\t\"D\n\rFUpdateBinary\x12\x0f\n\x07\x43hunkId\x18\x01 \x01(\r\x12\x10\n\x08\x43hunkMax\x18\x02 \x01(\r\x12\x10\n\x08RomChunk\x18\x03 \x01(\x0c\"u\n\rFChunxMessage\x12\x13\n\x0bMessageType\x18\x01 \x01(\r\x12\x1c\n\x07Version\x18\x02 \x01(\x0b\x32\t.FVersionH\x00\x12&\n\x0cUpdateBinary\x18\x03 \x01(\x0b\x32\x0e.FUpdateBinaryH\x00\x42\t\n\x07Messageb\x06proto3')
)




_FVERSION = _descriptor.Descriptor(
  name='FVersion',
  full_name='FVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VersionString', full_name='FVersion.VersionString', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=50,
)


_FUPDATEBINARY = _descriptor.Descriptor(
  name='FUpdateBinary',
  full_name='FUpdateBinary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ChunkId', full_name='FUpdateBinary.ChunkId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ChunkMax', full_name='FUpdateBinary.ChunkMax', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RomChunk', full_name='FUpdateBinary.RomChunk', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=120,
)


_FCHUNXMESSAGE = _descriptor.Descriptor(
  name='FChunxMessage',
  full_name='FChunxMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MessageType', full_name='FChunxMessage.MessageType', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Version', full_name='FChunxMessage.Version', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UpdateBinary', full_name='FChunxMessage.UpdateBinary', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Message', full_name='FChunxMessage.Message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=122,
  serialized_end=239,
)

_FCHUNXMESSAGE.fields_by_name['Version'].message_type = _FVERSION
_FCHUNXMESSAGE.fields_by_name['UpdateBinary'].message_type = _FUPDATEBINARY
_FCHUNXMESSAGE.oneofs_by_name['Message'].fields.append(
  _FCHUNXMESSAGE.fields_by_name['Version'])
_FCHUNXMESSAGE.fields_by_name['Version'].containing_oneof = _FCHUNXMESSAGE.oneofs_by_name['Message']
_FCHUNXMESSAGE.oneofs_by_name['Message'].fields.append(
  _FCHUNXMESSAGE.fields_by_name['UpdateBinary'])
_FCHUNXMESSAGE.fields_by_name['UpdateBinary'].containing_oneof = _FCHUNXMESSAGE.oneofs_by_name['Message']
DESCRIPTOR.message_types_by_name['FVersion'] = _FVERSION
DESCRIPTOR.message_types_by_name['FUpdateBinary'] = _FUPDATEBINARY
DESCRIPTOR.message_types_by_name['FChunxMessage'] = _FCHUNXMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FVersion = _reflection.GeneratedProtocolMessageType('FVersion', (_message.Message,), dict(
  DESCRIPTOR = _FVERSION,
  __module__ = 'updater_pb2'
  # @@protoc_insertion_point(class_scope:FVersion)
  ))
_sym_db.RegisterMessage(FVersion)

FUpdateBinary = _reflection.GeneratedProtocolMessageType('FUpdateBinary', (_message.Message,), dict(
  DESCRIPTOR = _FUPDATEBINARY,
  __module__ = 'updater_pb2'
  # @@protoc_insertion_point(class_scope:FUpdateBinary)
  ))
_sym_db.RegisterMessage(FUpdateBinary)

FChunxMessage = _reflection.GeneratedProtocolMessageType('FChunxMessage', (_message.Message,), dict(
  DESCRIPTOR = _FCHUNXMESSAGE,
  __module__ = 'updater_pb2'
  # @@protoc_insertion_point(class_scope:FChunxMessage)
  ))
_sym_db.RegisterMessage(FChunxMessage)


# @@protoc_insertion_point(module_scope)
